
%%%%%%%%%%%%% Subroutine to compute the aero loads convergence %%%%%
clear all
close all
clc

% 1
D1=load('ConvergenceWR_P3.dat');

% 2
D2=load('Convergence-powerWR_P3.dat');
 

figure(1)
plot(D1(:,2),'--ks','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',5)
hold on
plot(D2(:,2),'--rs','LineWidth',2,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',5)
xlabel('iteration ','fontsize',14)
ylabel('\eta','fontsize',20)
legend('Optimal 1','Optimal 2','fontsize',14,'Location','Best')            
figure(2)
plot(D1(:,5)/3.015,'--ks','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',5)
hold on
plot(D2(:,6)/3.015,'--rs','LineWidth',2,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',5)

xlabel('iteration ','fontsize',14)
ylabel('A/A_{bl}','fontsize',14)   
legend('Optimal 1','Optimal 2','fontsize',14,'Location','SouthEast')       

figure(3)
plot(D1(:,3)/4.17,'--ks','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',5)
hold on
plot(D2(:,3)/4.17,'--rs','LineWidth',2,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',5)

xlabel('iteration ','fontsize',14)
ylabel('L^*/L^*_{bl}','fontsize',14)   
legend('Optimal 1','Optimal 2','fontsize',14,'Location','SouthEast')   

figure(4)
plot(D1(:,6)/1.028,'--ks','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',5)
hold on
plot(D2(:,5)/1.028,'--rs','LineWidth',2,...
                'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',5)

xlabel('iteration ','fontsize',14)
ylabel('P^*/P^*_{bl}','fontsize',14)   
legend('Optimal 1','Optimal 2','fontsize',14,'Location','SouthEast')   

