!****************************************************
!*THIS MODULE CONTAINS ALL GLOBAL VARIABLES 
!****************************************************

MODULE global

INTEGER :: N_K

INTEGER :: NR, NC, NST, N_steps, N_W, NEL, N_DV

INTEGER :: wake_start, N_Avg_Begin

DOUBLE PRECISION :: chordL, spanL, V_ref, Omega, Red_Freq, PI, AR

DOUBLE PRECISION :: CP_IN_AVG, CL_AVG, CT_AVG 

DOUBLE PRECISION :: t_step, Cut_off, rho, EFF

DOUBLE PRECISION :: Area

DOUBLE PRECISION :: DX, DY

DOUBLE PRECISION :: ALPHA_MAX

DOUBLE PRECISION :: EFFICIENCY, LIFT_AVG, THRUST_AVG

DOUBLE PRECISION, DIMENSION(5) :: ELT, ELT2 

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: GEOMVAL, Varea

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: AreaElt

DOUBLE PRECISION :: twist_1,twist_2, bend

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: t

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: X0, Y0, Z0

DOUBLE PRECISION :: TW1amp, TW2amp, TW1phase, TW2phase

DOUBLE PRECISION :: TB1amp, TB2amp, TB1phase, TB2phase

DOUBLE PRECISION :: FLamp, FLphase

DOUBLE PRECISION :: PLamp, PLphase

DOUBLE PRECISION :: Pitchamp

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: Ones

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: KNOTS_VALUES

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: twist1, twist2

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: bend1, bend2

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: fore

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: Path_X, Path_Y, Path_Z 

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: Roll, Pitch

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: XX, YY, ZZ

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: XR, YR, ZR

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: XRb, YRb, ZRb

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: XC, YC, ZC

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: XCb, YCb, ZCb

DOUBLE PRECISION, DIMENSION(3,3) :: T_roll, T_pitch

DOUBLE PRECISION, DIMENSION(3,3) :: T_matrix

DOUBLE PRECISION, DIMENSION(12) :: INVAL

INTEGER :: i_time

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: U_KIN, V_KIN, W_KIN

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: Outward_X, Outward_Y, Outward_Z

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: Tau_X, Tau_Y, Tau_Z

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: N_drag_X, N_drag_Y, N_drag_Z

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: N_lift_X, N_lift_Y, N_lift_Z

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: ALPHA

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: X_Wake, Y_Wake, Z_Wake 

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: Circ 

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: Circ_Wake

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: C_mat, B_mat

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: NORM_FLOW

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: LL

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: C_mat_Wake, B_mat_Wake

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: Mat

INTEGER :: INFO

INTEGER, DIMENSION(:), ALLOCATABLE :: IPIV

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: R, G

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: VV

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: MVV

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: W_ind

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: MVV2

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: VV2

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: VV3

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: MVV3

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: Circ_foo

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: Circ_local

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: Sigma1

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: DFDT

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: POWER, CD, CL

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: DCP

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: C1_rollup

DOUBLE PRECISION, DIMENSION(:,:,:), ALLOCATABLE :: C2_rollup

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: DEL_X, DEL_Y, DEL_Z

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: MVV4, MVV5

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: VV4, VV5

DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: MDEL_X, MDEL_Y, MDEL_Z

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: t_spline, TW_spline, y2it1

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: y2it2, y2ib1, y2ib2

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: TW2_spline, B_spline, B2_spline

DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: Y_spline, Y2_spline, Y3_spline, Y4_spline

END MODULE
